// USER DETAILS
export const ALL_USERS_DETAILS_REQUEST = 'ALL_USERS_DETAILS_REQUEST'
export const ALL_USERS_DETAILS_SUCCESS = 'ALL_USERS_DETAILS_SUCCESS'
export const ALL_USERS_DETAILS_FAIL = 'ALL_USERS_DETAILS_FAIL'

// USER UPDATE
export const UPDATE_ALL_USERS_REQUEST = 'UPDATE_ALL_USERS_REQUEST'
export const UPDATE_ALL_USERS_SUCCESS = 'UPDATE_ALL_USERS_SUCCESS'
export const UPDATE_ALL_USERS_FAIL = 'UPDATE_ALL_USERS_FAIL'

// Dashboard Data 
export const ALL_DEFAULT_DATA_FOR_DASHBOARD_REQUEST = 'ALL_DEFAULT_DATA_FOR_DASHBOARD_REQUEST'
export const ALL_DEFAULT_DATA_FOR_DASHBOARD_SUCCESS = 'ALL_DEFAULT_DATA_FOR_DASHBOARD_SUCCESS'
export const ALL_DEFAULT_DATA_FOR_DASHBOARD_FAIL = 'ALL_DEFAULT_DATA_FOR_DASHBOARD_FAIL'

// Dashboard Data 
export const DEVICE_ACTION_REQUEST = 'DEVICE_ACTION_REQUEST'
export const DEVICE_ACTION_SUCCESS = 'DEVICE_ACTION_SUCCESS'
export const DEVICE_ACTION_FAIL = 'DEVICE_ACTION_FAIL'

// Dashboard Data 
export const DEVICE_DELETE_REQUEST = 'DEVICE_DELETE_REQUEST'
export const DEVICE_DELETE_SUCCESS = 'DEVICE_DELETE_SUCCESS'
export const DEVICE_DELETE_FAIL = 'DEVICE_DELETE_FAIL'


// ASSIGN_DELETE_DATA_ACTION_REQUEST
export const DEVICE_DELETE_DATA_ACTION_REQUEST = 'DEVICE_DELETE_DATA_ACTION_REQUEST'
export const DEVICE_DELETE_DATA_ACTION_SUCCESS = 'DEVICE_DELETE_DATA_ACTION_SUCCESS'
export const DEVICE_DELETE_DATA_ACTION_FAIL = 'DEVICE_DELETE_DATA_ACTION_FAIL'

// USER_DELETE_DATA_ACTION_REQUEST
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_REQUEST_SUCCESS = 'USER_DELETE_REQUEST_SUCCESS'
export const USER_DELETE_REQUEST_FAIL = 'USER_DELETE_REQUEST_FAIL'
