// USER DETAILS
export const ALL_USERS_DETAILS_REQUEST = 'ALL_USERS_DETAILS_REQUEST'
export const ALL_USERS_DETAILS_SUCCESS = 'ALL_USERS_DETAILS_SUCCESS'
export const ALL_USERS_DETAILS_FAIL = 'ALL_USERS_DETAILS_FAIL'

// USER UPDATE
export const UPDATE_ALL_USERS_REQUEST = 'UPDATE_ALL_USERS_REQUEST'
export const UPDATE_ALL_USERS_SUCCESS = 'UPDATE_ALL_USERS_SUCCESS'
export const UPDATE_ALL_USERS_FAIL = 'UPDATE_ALL_USERS_FAIL'