// //UPLOAD DEVICE REGISTRATION DETAILS

export const GET_DEVICE_REQUEST_RESET = "GET_DEVICE_REQUEST_RESET"
export const GET_DEVICE_REQUEST = "GET_DEVICE_REQUEST"
export const GET_DEVICE_REQUEST_SUCCESS = "GET_DEVICE_REQUEST_SUCCESS"
export const GET_DEVICE_REQUEST_FAIL ="GET_DEVICE_REQUEST_FAIL"

export const REGISTER_NEW_DEVICE_REQUEST = "REGISTER_NEW_DEVICE_REQUEST"
export const REGISTER_NEW_DEVICE_SUCCESS = "REGISTER_NEW_DEVICE_SUCCESS"
export const REGISTER_NEW_DEVICE_FAIL = "REGISTER_NEW_DEVICE_FAIL"
export const REGISTER_NEW_DEVICE_RESET = "REGISTER_NEW_DEVICE_RESET"