//UPLOAD DEVICE REGISTRATION DETAILS

export const REGISTER_DEVICE_DETAILS_REQUEST = "GET_DEVICE_DETAILS_REQUEST"
export const REGISTER_DEVICE_DETAILS_SUCCESS = "GET_DEVICE_DETAILS_SUCCESS"
export const REGISTER_DEVICE_DETAILS_FAIL = "GET_DEVICE_DETAILS_FAIL"