// // //UPLOAD DEVICE REGISTRATION DETAILS

// export const GET_DEVICE_REQUEST_RESET = "GET_DEVICE_REQUEST_RESET"
// export const GET_DEVICE_REQUEST = "GET_DEVICE_REQUEST"
// export const GET_DEVICE_REQUEST_SUCCESS = "GET_DEVICE_REQUEST_SUCCESS"
// export const GET_DEVICE_REQUEST_FAIL ="GET_DEVICE_REQUEST_FAIL"

export const DEVICE_FAIL = "DEVICE_FAIL"
export const DEVICE_REQUEST = "DEVICE_REQUEST"
export const DEVICE_SUCCESS = "DEVICE_SUCCESS"

// GET MODEL CODE
export const GET_MODEL_CODE_REQUEST = 'GET_MODEL_CODE_REQUEST'
export const GET_MODEL_CODE_SUCCESS = 'GET_MODEL_CODE_SUCCESS'
export const GET_MODEL_CODE_FAIL = 'GET_MODEL_CODE_FAIL'

export const REGISTER_NEW_DEVICE_REQUEST = "REGISTER_NEW_DEVICE_REQUEST "
export const REGISTER_NEW_DEVICE_FAIL = "REGISTER_NEW_DEVICE_FAIL"
export const REGISTER_NEW_DEVICE_SUCCESS = "REGISTER_NEW_DEVICE_SUCCESS"

export const GET_ALL_LOG_BY_CODE_REQUEST = 'GET_ALL_LOG_BY_CODE_REQUEST'
export const GET_ALL_LOG_BY_CODE_SUCCESS = 'GET_ALL_LOG_BY_CODE_SUCCESS'
export const GET_ALL_LOG_BY_CODE_FAIL = 'GET_ALL_LOG_BY_CODE_FAIL'