// STATE NAME DATA
export const DISPATCH_DETAILS_REQUEST = 'DISPATCH_DETAILS_REQUEST'
export const DISPATCH_DETAILS_SUCCESS = 'DISPATCH_DETAILS_SUCCESS'
export const DISPATCH_DETAILS_FAIL = 'DISPATCH_DETAILS_FAIL'


export const GET_DISPATCH_DETAILS_DATA_REQUEST = 'GET_DISPATCH_DETAILS_DATA_REQUEST'
export const GET_DISPATCH_DETAILS_DATA_SUCCESS = 'GET_DISPATCH_DETAILS_DATA_SUCCESS'
export const GET_DISPATCH_DETAILS_DATA_FAIL = 'GET_DISPATCH_DETAILS_DATA_FAIL'

export const GET_DISPATCH_DETAILS_DATA_BYID_REQUEST = 'GET_DISPATCH_DETAILS_DATA_BYID_REQUEST'
export const GET_DISPATCH_DETAILS_DATA_BYID_SUCCESS = 'GET_DISPATCH_DETAILS_DATA_BYID_SUCCESS'
export const GET_DISPATCH_DETAILS_DATA_BYID_FAIL = 'GET_DISPATCH_DETAILS_DATA_BYID_FAIL'


export const PRODUCTION_DETAILS_REQUEST = 'PRODUCTION_DETAILS_REQUEST'
export const PRODUCTION_DETAILS_SUCCESS = 'PRODUCTION_DETAILS_SUCCESS'
export const PRODUCTION_DETAILS_FAIL = 'PRODUCTION_DETAILS_FAIL'

export const GET_PRODUCTION_DETAILS_DATA_REQUEST = 'GET_PRODUCTION_DETAILS_DATA_REQUEST'
export const GET_PRODUCTION_DETAILS_DATA_SUCCESS = 'GET_PRODUCTION_DETAILS_DATA_SUCCESS'
export const GET_PRODUCTION_DETAILS_DATA_FAIL = 'GET_PRODUCTION_DETAILS_DATA_FAIL'