// GET ALL TICKETS DATA
export const GET_ALL_TICKETS_DATA_REQUEST = "GET_ALL_TICKETS_DATA_REQUEST"
export const GET_ALL_TICKETS_DATA_SUCCESS = "GET_ALL_TICKETS_DATA_SUCCESS"
export const GET_ALL_TICKETS_DATA_FAIL = "GET_ALL_TICKETS_DATA_FAIL"

// PUT OR UPDATE STATUS DATA
export const UPDATE_STATUS_DATA_REQUEST = "UPDATE_STATUS_DATA_REQUEST"
export const UPDATE_STATUS_DATA_SUCCESS = "UPDATE_STATUS_DATA_SUCCESS"
export const UPDATE_STATUS_DATA_FAIL = "UPDATE_STATUS_DATA_FAIL"


// DELETE OR UPDATE STATUS DATA
export const DELETE_STATUS_DATA_REQUEST = "DELETE_STATUS_DATA_REQUEST"
export const DELETE_STATUS_DATA_SUCCESS = "DELETE_STATUS_DATA_SUCCESS"
export const DELETE_STATUS_DATA_FAIL = "DELETE_STATUS_DATA_FAIL"


// TICKET DETAILS BY ID 
export const GET_TICKET_DETAILS_BY_ID_REQUEST = "GET_TICKET_DETAILS_BY_ID_REQUEST"
export const GET_TICKET_DETAILS_BY_ID_SUCCESS = "GET_TICKET_DETAILS_BY_ID_SUCCESS"
export const GET_TICKET_DETAILS_BY_ID_FAIL = "GET_TICKET_DETAILS_BY_ID_FAIL"

// UPLOAD DOCX 
export const POST_DOC_BY_SERVICE_REQUEST = "POST_DOC_BY_SERVICE_REQUEST"
export const POST_DOC_BY_SERVICE_SUCCESS = "POST_DOC_BY_SERVICE_SUCCESS"
export const POST_DOC_BY_SERVICE_FAIL = "POST_DOC_BY_SERVICE_FAIL"

// INSTALATION REPORT DATA 
export const INSTALLATION_REPORT_REQUEST = "INSTALLATION_REPORT_REQUEST"
export const INSTALLATION_REPORT_REQUEST_SUCCESS = "INSTALLATION_REPORT_REQUEST_SUCCESS"
export const INSTALLATION_REPORT_REQUEST_FAIL = "INSTALLATION_REPORT_REQUEST_FAIL"