// store data 
export const STORE_SYSTEM_REQUEST = 'STORE_SYSTEM_REQUEST'
export const STORE_SYSTEM_SUCCESS = 'STORE_SYSTEM_SUCCESS'
export const STORE_SYSTEM_FAIL = 'STORE_SYSTEM_FAIL'


// // store data 
// export const DATA_FROM_DEVICEID_REQUEST = 'DATA_FROM_DEVICEID_REQUEST'
// export const DATA_FROM_DEVICEID_SUCCESS = 'DATA_FROM_DEVICEID_SUCCESS'
// export const DATA_FROM_DEVICEID_FAIL = 'DATA_FROM_DEVICEID_FAIL'


// store data 
export const ALL_HOSPITAL_DATA_REQUEST = 'ALL_HOSPITAL_DATA_REQUEST'
export const ALL_HOSPITAL_DATA_SUCCESS = 'ALL_HOSPITAL_DATA_SUCCESS'
export const ALL_HOSPITAL_DATA_FAIL = 'ALL_HOSPITAL_DATA_FAIL'


// store data 
export const PUT_ALL_STORE_DATA_REQUEST = 'PUT_ALL_STORE_DATA_REQUEST'
export const PUT_ALL_STORE_DATA_SUCCESS = 'PUT_ALL_STORE_DATA_SUCCESS'
export const PUT_ALL_STORE_DATA_FAIL = 'PUT_ALL_STORE_DATA_FAIL'