// ADMIN LOGIN
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'

// ADMIN LOGOUT
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
export const ADMIN_LOGOUT_FAIL = 'ADMIN_LOGOUT_FAIL'

// ADMIN REGISTER
export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST"
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS"
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL"

// ADMIN PASSWORD FORGET
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_REQUEST_SUCCESS = 'FORGET_PASSWORD_REQUEST_SUCCESS'
export const FORGET_PASSWORD_REQUEST_FAIL = 'FORGET_PASSWORD_REQUEST_FAIL'
export const FORGET_PASSWORD_RESET_STATE = 'FORGET_PASSWORD_RESET_STATE'

// ADMIN PASSWORD RESET
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS'
export const RESET_PASSWORD_REQUEST_FAIL = 'RESET_PASSWORD_REQUEST_FAIL'

// ADMIN UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_REQUEST_SUCCESS = 'UPDATE_PROFILE_REQUEST_SUCCESS'
export const UPDATE_PROFILE_REQUEST_FAIL = 'UPDATE_PROFILE_REQUEST_FAIL'
