export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_REQUEST_SUCCESS = 'GET_PROJECT_REQUEST_SUCCESS'
export const GET_PROJECT_REQUEST_FAIL = 'GET_PROJECT_REQUEST_FAIL'

export const GET_ALL_LOG_BY_CODE_REQUEST = 'GET_ALL_LOG_BY_CODE_REQUEST'
export const GET_ALL_LOG_BY_CODE_SUCCESS = 'GET_ALL_LOG_BY_CODE_SUCCESS'
export const GET_ALL_LOG_BY_CODE_FAIL = 'GET_ALL_LOG_BY_CODE_FAIL'

export const UPLOAD_NEW_PROJECT_REQUEST = 'UPLOAD_NEW_PROJECT_REQUEST'
export const UPLOAD_NEW_PROJECT_REQUEST_SUCCESS = 'UPLOAD_NEW_PROJECT_REQUEST_SUCCESS'
export const UPLOAD_NEW_PROJECT_REQUEST_FAIL = 'UPLOAD_NEW_PROJECT_REQUEST_FAIL'

export const GET_LOG_COUNT_REQUEST = 'GET_LOG_COUNT_REQUEST'
export const GET_LOG_COUNT_SUCCESS = 'GET_LOG_COUNT_SUCCESS'
export const GET_LOG_COUNT_FAIL = 'GET_LOG_COUNT_FAIL'

export const GET_LOG_COUNT_BY_DATE_REQUEST = 'GET_LOG_COUNT_BY_DATE_REQUEST'
export const GET_LOG_COUNT_BY_DATE_SUCCESS = 'GET_LOG_COUNT_BY_DATE_SUCCESS'
export const GET_LOG_COUNT_BY_DATE_FAIL = 'GET_LOG_COUNT_BY_DATE_FAIL'

export const GET_ERROR_WRT_OS_REQUEST = 'GET_ERROR_WRT_OS_REQUEST'
export const GET_ERROR_WRT_OS_REQUEST_SUCCESS = 'GET_ERROR_WRT_OS_REQUEST_SUCCESS'
export const GET_ERROR_WRT_OS_REQUEST_FAIL = 'GET_ERROR_WRT_OS_REQUEST_FAIL'

export const GET_ERROR_COUNT_BY_VERSION_REQUEST = 'GET_ERROR_COUNT_BY_VERSION_REQUEST'
export const GET_ERROR_COUNT_BY_VERSION_REQUEST_SUCCESS = 'GET_ERROR_COUNT_BY_VERSION_REQUEST_SUCCESS'
export const GET_ERROR_COUNT_BY_VERSION_REQUEST_FAIL = 'GET_ERROR_COUNT_BY_VERSION_REQUEST_FAIL'

export const GET_DEVICE_INFO_REQUEST = 'GET_DEVICE_INFO_REQUEST'
export const GET_DEVICE_INFO_REQUEST_SUCCESS = 'GET_DEVICE_INFO_REQUEST_SUCCESS'
export const GET_DEVICE_INFO_REQUEST_FAIL = 'GET_DEVICE_INFO_REQUEST_FAIL'

export const GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST = 'GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST'
export const GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST_SUCCESS = 'GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST_SUCCESS'
export const GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST_FAIL = 'GET_LOG_MSG_OCCURENCE_COUNT_WRT_DATE_REQUEST_FAIL'

export const UPLOAD_NEW_PROJECT_REQUEST_RESET = 'UPLOAD_NEW_PROJECT_REQUEST_RESET'


